export const MOCK_CLIPS = [
    {
        id: 'c01',
        tags: ['#Fantasy', '#Action'],
        caption: 'The one who walks away from Omelas 🌙',
        gradientClass: 'clip-grad-1',
        show: { name: 'Breaking Bad', description: 'A high school chemistry teacher turned drug kingpin navigates the criminal underworld with his former student.', genres: ['Crime', 'Drama', 'Thriller'], rating: 9.5 },
        youtubeUrl: 'https://youtube.com',
        commentCount: 12,
        comments: [
            { user: '@UserAccount', initials: 'U', text: "Doesn't this come from the pilot episode??", replyCount: 2, replies: [] },
            { user: '@VeteranWatcher', initials: 'V', text: "I have seen the series too many times and it's still so good.", replyCount: 0, replies: [] },
        ],
    },
    {
        id: 'c02',
        tags: ['#Crime', '#Drama'],
        caption: 'Walter loses his mind in the desert 🏜️',
        gradientClass: 'clip-grad-2',
        show: { name: 'Breaking Bad', description: 'A high school chemistry teacher turned drug kingpin navigates the criminal underworld with his former student.', genres: ['Crime', 'Drama', 'Thriller'], rating: 9.5 },
        youtubeUrl: 'https://youtube.com',
        commentCount: 7,
        comments: [
            { user: '@ChemistryFan', initials: 'C', text: 'The acting here is absolutely unreal.', replyCount: 0, replies: [] },
        ],
    },
    {
        id: 'c03',
        tags: ['#Iconic', '#Scene'],
        caption: 'Jesse screams into the void 😤',
        gradientClass: 'clip-grad-3',
        show: { name: 'Breaking Bad', description: 'A high school chemistry teacher turned drug kingpin navigates the criminal underworld with his former student.', genres: ['Crime', 'Drama', 'Thriller'], rating: 9.5 },
        youtubeUrl: 'https://youtube.com',
        commentCount: 3,
        comments: [],
    },
    {
        id: 'c04',
        tags: ['#Legal', '#Comedy'],
        caption: 'Saul does Saul things 🎭',
        gradientClass: 'clip-grad-4',
        show: { name: 'Better Call Saul', description: 'A small-time lawyer schemes his way into the criminal underworld, slowly becoming the morally flexible Saul Goodman.', genres: ['Crime', 'Drama', 'Legal'], rating: 9.0 },
        youtubeUrl: 'https://youtube.com',
        commentCount: 5,
        comments: [
            { user: '@LegalEagle', initials: 'L', text: 'Best spinoff ever made, no contest.', replyCount: 1, replies: [{ user: '@BetterCallMe', initials: 'B', text: 'Agree 100%.' }] },
        ],
    },
    {
        id: 'c05',
        tags: ['#Science', '#Heist'],
        caption: 'The magnet scene 🧲',
        gradientClass: 'clip-grad-5',
        show: { name: 'Breaking Bad', description: 'A high school chemistry teacher turned drug kingpin navigates the criminal underworld with his former student.', genres: ['Crime', 'Thriller'], rating: 9.5 },
        youtubeUrl: 'https://youtube.com',
        commentCount: 21,
        comments: [
            { user: '@Physics101', initials: 'P', text: "Science doesn't actually work like that but WHO CARES.", replyCount: 0, replies: [] },
        ],
    },
    {
        id: 'c06',
        tags: ['#SciFi', '#Comedy'],
        caption: 'Bender realized he could bend anything 🤯💪',
        gradientClass: 'clip-grad-6',
        show: { name: 'Futurama', description: 'Philip J. Fry, a pizza delivery boy, is accidentally frozen in 1999 and thawed out on New Year\'s Eve 2999.', genres: ['Cyberpunk', 'Dark Comedy', 'Parody', 'Sitcom', 'Sci-Fi', 'Adventure'], rating: 8.9 },
        youtubeUrl: 'https://youtube.com',
        commentCount: 5,
        comments: [
            { user: '@UserAccount', initials: 'U', text: "Doesn't this comes from the pilot episode??", replyCount: 2, replies: [] },
            { user: '@VeteranWatcher', initials: 'V', text: "I have seen the series too many times and it's still so good.", replyCount: 0, replies: [] },
            {
                user: '@AvidTrashIsekaiConnosieur', initials: 'A', text: '67', replyCount: 2,
                replies: [
                    { user: '@EmoTable', initials: 'E', text: 'Nahh, get out of here 🔥' },
                    { user: '@YourFriendlyNeighbor', initials: 'Y', text: 'Bro' },
                ],
            },
        ],
    },
    {
        id: 'c07',
        tags: ['#SciFi', '#Nostalgia'],
        caption: 'Fry falls into the cryo-tube 🧊',
        gradientClass: 'clip-grad-7',
        show: { name: 'Futurama', description: 'Philip J. Fry, a pizza delivery boy, is accidentally frozen in 1999 and thawed out on New Year\'s Eve 2999.', genres: ['Sci-Fi', 'Comedy', 'Adventure'], rating: 8.9 },
        youtubeUrl: 'https://youtube.com',
        commentCount: 14,
        comments: [],
    },
    {
        id: 'c08',
        tags: ['#Action', '#SciFi'],
        caption: 'Leela kicks a bureaucrat 🦵',
        gradientClass: 'clip-grad-8',
        show: { name: 'Futurama', description: 'Philip J. Fry, a pizza delivery boy, is accidentally frozen in 1999 and thawed out on New Year\'s Eve 2999.', genres: ['Action', 'Sci-Fi', 'Comedy'], rating: 8.9 },
        youtubeUrl: 'https://youtube.com',
        commentCount: 9,
        comments: [],
    },
    {
        id: 'c09',
        tags: ['#Sad', '#Iconic'],
        caption: 'The tearful farewell 😢',
        gradientClass: 'clip-grad-9',
        show: { name: 'Futurama', description: 'The most devastating episode ever written for a cartoon. Seymour waits outside for his human.', genres: ['Drama', 'Sci-Fi', 'Comedy'], rating: 9.1 },
        youtubeUrl: 'https://youtube.com',
        commentCount: 88,
        comments: [
            { user: '@CryingAgain', initials: 'C', text: "I will never recover from this episode. Never.", replyCount: 0, replies: [] },
        ],
    },
    {
        id: 'c10',
        tags: ['#Satire', '#Politics'],
        caption: "Nixon's head in a jar campaigns 🗳️",
        gradientClass: 'clip-grad-10',
        show: { name: 'Futurama', description: 'Democracy persists into the 31st century, somehow — with familiar faces.', genres: ['Satire', 'Comedy', 'Sci-Fi'], rating: 8.9 },
        youtubeUrl: 'https://youtube.com',
        commentCount: 6,
        comments: [],
    },
    {
        id: 'c11',
        tags: ['#Crime', '#Street'],
        caption: 'The confession tape 📼',
        gradientClass: 'clip-grad-1',
        show: { name: 'The Wire', description: "Baltimore's drug trade and the police department that can't quite keep up.", genres: ['Crime', 'Drama'], rating: 9.3 },
        youtubeUrl: 'https://youtube.com',
        commentCount: 4,
        comments: [],
    },
    {
        id: 'c12',
        tags: ['#Iconic', '#Crime'],
        caption: 'Omar whistles down the block 🎵',
        gradientClass: 'clip-grad-3',
        show: { name: 'The Wire', description: "Baltimore's drug trade and the police department that can't quite keep up.", genres: ['Crime', 'Drama'], rating: 9.3 },
        youtubeUrl: 'https://youtube.com',
        commentCount: 17,
        comments: [],
    },
    {
        id: 'c13',
        tags: ['#Crime', '#Detective'],
        caption: "McNulty's famous scene 🥃",
        gradientClass: 'clip-grad-5',
        show: { name: 'The Wire', description: "Baltimore's drug trade and the police department that can't quite keep up.", genres: ['Crime', 'Drama'], rating: 9.3 },
        youtubeUrl: 'https://youtube.com',
        commentCount: 11,
        comments: [],
    },
    {
        id: 'c14',
        tags: ['#Fantasy', '#Shocking'],
        caption: 'The Red Wedding 😱',
        gradientClass: 'clip-grad-2',
        show: { name: 'Game of Thrones', description: 'A wedding celebration turns into a massacre that changes Westeros forever.', genres: ['Fantasy', 'Drama', 'Action'], rating: 9.5 },
        youtubeUrl: 'https://youtube.com',
        commentCount: 302,
        comments: [
            { user: '@StillNotOverIt', initials: 'S', text: "Ten years later and this still hurts.", replyCount: 0, replies: [] },
        ],
    },
    {
        id: 'c15',
        tags: ['#Fantasy', '#Action'],
        caption: 'Arya vs the Night King ⚡',
        gradientClass: 'clip-grad-4',
        show: { name: 'Game of Thrones', description: 'One leap, one dagger, one decision that saves the living from eternal night.', genres: ['Fantasy', 'Action'], rating: 9.5 },
        youtubeUrl: 'https://youtube.com',
        commentCount: 255,
        comments: [],
    },
];

export const MOCK_FRIENDS = [
    { uid: 'uid_2', username: 'chemcrazy', displayName: 'Carlos Mendes', initial: 'C', color: '#c0392b' },
    { uid: 'uid_3', username: 'finnwatches', displayName: 'Finn Okafor', initial: 'F', color: '#7c3aed' },
    { uid: 'uid_4', username: 'gigi_binge', displayName: 'Gianna Russo', initial: 'G', color: '#9333ea' },
    { uid: 'uid_5', username: 'just_jordan', displayName: 'Jordan Lee', initial: 'J', color: '#16a34a' },
    { uid: 'uid_6', username: 'zaracinephile', displayName: 'Zara Whitfield', initial: 'Z', color: '#6b7280' },
];

export const MOCK_USER = {
    uid: 'mock-uid-01',
    username: 'azharha77',
    displayName: 'Azhar Hafiza',
    email: 'azhar@example.com',
    avatarUrl: null,
    bio: 'TV obsessive. Breaking Bad apologist. Always hunting for the next great cliffhanger.',
    joinedAt: '2026-01-12T00:00:00Z',
    friendIds: ['uid_2', 'uid_3', 'uid_4'],
};

export const MOCK_WATCHLIST = [
    { id: 'w01', movieId: 1396, title: 'Breaking Bad', posterPath: null, addedAt: '2026-03-01T00:00:00Z', status: 'watching' },
    { id: 'w02', movieId: 1405, title: 'Better Call Saul', posterPath: null, addedAt: '2026-02-20T00:00:00Z', status: 'watching' },
    { id: 'w03', movieId: 1438, title: 'The Wire', posterPath: null, addedAt: '2026-02-10T00:00:00Z', status: 'planned' },
    { id: 'w04', movieId: 1668, title: 'Futurama', posterPath: null, addedAt: '2026-01-25T00:00:00Z', status: 'watched' },
    { id: 'w05', movieId: 1399, title: 'Game of Thrones', posterPath: null, addedAt: '2026-01-15T00:00:00Z', status: 'watched' },
];
